# Generated by Django 6.0.3 on 2026-03-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='code',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end',
        ),
    ]
