# Generated by Django 6.0.3 on 2026-03-18 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cinema.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('purchased', 'Purchased')], default='available', max_length=9),
        ),
    ]
