# Generated by Django 6.0.3 on 2026-03-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_ticket_session_alter_seat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
    ]
